Main/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.conf import settings
from .import views
from .views import order_finish, create_order, ProfileDeletedView

urlpatterns = [
    path('', views.index.as_view(), name='index'),
    path('catalog/', views.catalog.as_view(), name='catalog'),
    path('contact/', views.contact, name='contact'),
    path('login/', views.login.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register.as_view(), name='register'),
    path('catalog/create', views.createproduct.as_view(), name='createproduct'),
    path('api/', views.api, name='api'),
    path('apidelete', views.apidelete, name='apidelete'),
    path('apicreate', views.apicreate, name='apicreate'),
    path('apiedit', views.apiedit, name='apiedit'),
    path('apiselectmany', views.apiselectmany, name='apiselectmany'),
    path('apiselectone', views.apiselectone, name='apiselectone'),
    path('catalog/<int:pk>/', views.productt.as_view(), name='productt'),
    path('catalog/category/<int:category_id>/', views.FilteredCatalogView.as_view(), name='category'),
    path('catalog/tag/<int:pk>/', views.TagDetailView.as_view(), name='tag'),
    path('catalog/<int:pk>/update', views.update.as_view(), name='update'),
    path('catalog/<int:pk>/delete', views.delete.as_view(), name='delete'),
    path('catalog/createcategory', views.createcategory.as_view(), name='createcategory'),
    path('catalog/CreateTag', views.CreateTag.as_view(), name='CreateTag'),
    path('filter_by_price/', views.filter_by_price, name='filter_by_price'),
    path('order/', views.order.as_view(), name='order'),
    path('create-order/', create_order, name='create_order'),
    path('order-finish/', order_finish, name='order_finish'),
    path('order/create', views.createorder.as_view(), name='createorder'),
    path('order/detail/<int:pk>/', views.detailorder.as_view(), name='detailorder'),
    path('order/update/<int:pk>/', views.updateorder.as_view(), name='updateorder'),
    path('order/delete/<int:pk>/', views.deleteorder.as_view(), name='deleteorder'),

    path('cart/', views.basket_info, name='cart'),
    path('cart/add/<int:product_id>/', views.basket_add, name='add_basket_prod'),
    path('cart/remove/<int:product_id>/', views.basket_remove, name='remove_basket_prod'),
    path('cart/clear/', views.basket_clear, name='clear_basket_prod'),
    path('cart/finish/', order_finish, name='order_finish'),

    path('about_us/', views.about_us, name='about_us'),

    path('profile/', views.profile, name='profile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('delete-profile/', views.ProfileDeleteView.as_view(), name='delete_profile'),
    path('profile-deleted/', ProfileDeletedView.as_view(), name='profile_deleted'),

    # Api
    path('api/', views.api, name='api'),
    # категории
    path('api/category/', views.ApiCategoryList.as_view(), name='api_category'),
    path('api/category/create/', views.ApiCategoryCreate.as_view(), name='api_category_create'),
    path('api/category/<int:pk>/', views.ApiCategoryDetail.as_view(), name='api_category_detail'),
    path('api/category/update/<int:pk>/', views.ApiCategoryUpdate.as_view(), name='api_category_update'),
    path('api/category/delete/<int:pk>/', views.ApiCategoryDelete.as_view(), name='api_category_delete'),
    # продукты
    path('api/product/', views.ApiModel_and_tochkaList.as_view(), name='api_product'),
    path('api/product/create/', views.ApiModel_and_tochkaCreate.as_view(), name='api_product_create'),
    path('api/product/<int:pk>/', views.ApiModel_and_tochkaDetail.as_view(), name='api_product_detail'),
    path('api/product/update/<int:pk>/', views.ApiCategoryUpdate.as_view(), name='api_product_update'),
    path('api/product/delete/<int:pk>/', views.ApiModel_and_tochkaDelete.as_view(), name='api_product_delete'),
    # тэги
    path('api/tag/', views.ApiTagList.as_view(), name='api_tag'),
    path('api/tag/create/', views.ApiTagCreate.as_view(), name='api_tag_create'),
    path('api/tag/<int:pk>/', views.ApiTagDetail.as_view(), name='api_tag_detail'),
    path('api/tag/update/<int:pk>/', views.ApiTagUpdate.as_view(), name='api_tag_update'),
    path('api/tag/delete/<int:pk>/', views.ApiModel_and_tochkaDelete.as_view(), name='api_tag_delete'),
]

MyShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Main.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=45, verbose_name='Название')
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'Категории'

    def get_absolute_url(self):
        return '/catalog'


class Model_and_tochka(models.Model):
    category = models.ForeignKey(Category, on_delete=models.PROTECT, verbose_name='Категория', null=True)
    name = models.CharField(max_length=45, default='Product', verbose_name='Название')
    description = models.TextField(blank=True, verbose_name='Описание')
    price = models.FloatField(default=10, verbose_name='Цена')
    data_add = models.DateField(auto_now_add=True, verbose_name='Дата добавления')
    data_update = models.DateTimeField(auto_now=True, verbose_name='Дата изменения')
    exist = models.BooleanField(default=True, verbose_name='Существует?')
    photo = models.ImageField(upload_to='image/%Y/%m/%d', null=True, verbose_name='Изображения', blank=True)
    country_of_origin = models.CharField(max_length=100, blank=True, null=True, verbose_name='Страна производителя')

    def __str__(self):
        return f'{self.name} - {self.price}'

    def get_absolute_url(self):
        return f'/catalog/{self.pk}'

    def delete(self, using=None, keep_parents=False):
        self.exist = False
        self.save()

    class Meta:
        verbose_name = 'товар'
        verbose_name_plural = 'Товары'
        ordering = ['-price', 'name']


class Tag(models.Model):
    name = models.CharField(max_length=45, verbose_name='Название')
    description = models.TextField(blank=True, verbose_name='Описание')
    products = models.ManyToManyField('Model_and_tochka', related_name='tags', verbose_name='Товары')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/catalog/tag/{self.pk}'

    class Meta:
        verbose_name = 'тег'
        verbose_name_plural = 'Теги'
        ordering = ['name']



class Order(models.Model):
    STATUS_CHOICES = [
        ('processing', 'В обработке'),
        ('completed', 'Выполнен'),
        ('cancelled', 'Отменён'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь', null=True, blank=True)
    email = models.EmailField(verbose_name='Email пользователя', blank=True, null=True)
    creation_date = models.DateField(auto_now_add=True, verbose_name='Дата создания')
    products = models.ManyToManyField('Model_and_tochka', through='OrderItem', verbose_name='Товары')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='processing', verbose_name='Статус заказа')
    exist = models.BooleanField(default=True, verbose_name='Существует?')

    def __str__(self):
        return f'Order by {self.user.username if self.user else "Unknown"} on {self.creation_date}'

    def save(self, *args, **kwargs):
        if self.user:
            self.email = self.user.email  # Автоматически заполняем поле email почтой пользователя
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'заказ'
        verbose_name_plural = 'Заказы'




class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name='Заказ')
    product = models.ForeignKey('Model_and_tochka', on_delete=models.CASCADE, verbose_name='Товар и его цена')
    quantity = models.PositiveIntegerField(verbose_name='Количество товаров на позиции', default=1)


    def __str__(self):
        return f'{self.order} - {self.product}'

    class Meta:
        verbose_name = 'позиция заказа'
        verbose_name_plural = 'Позиции заказа'

Main/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from .models import Model_and_tochka, Category, Tag, Order, OrderItem
from django.forms import ModelForm, TextInput, Textarea, inlineformset_factory
from django import forms
from django.contrib.auth.models import User
from .models import Order


class Model_and_tochkaForm(ModelForm):


    class Meta:
        model = Model_and_tochka
        fields = ['category', 'name', 'description', 'price', 'photo', 'country_of_origin']
        widgets = {
            "name": TextInput(attrs={
                'class': 'form-control py-6',
                'placeholder': ''
            }),
            "description": Textarea(attrs={
                'class': 'form-control'
            })
        }

class CategoryForm(ModelForm):

    class Meta:
        model = Category
        fields = ['description', 'name']
        widgets = {
            "name": TextInput(attrs={
                'class': 'form-control py-6',
                'placeholder': ''
            }),
            "description": Textarea(attrs={
                'class': 'form-control'
            })
    }
class TagForm(ModelForm):

    class Meta:
        model = Tag
        fields = ['description', 'name', 'products']
        widgets = {
            "name": TextInput(attrs={
                'class': 'form-control py-6',
                'placeholder': ''
            }),
            "description": Textarea(attrs={
                'class': 'form-control'
            })
    }

PROD_MAX_COUNT = [(i, str(i)) for i in range(1, 25)]


class BasketAddProductForm(forms.Form):
    count_prod = forms.TypedChoiceField(choices=PROD_MAX_COUNT, coerce=int, label='Количество')
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['user', 'status']  # Поля для выбора пользователя и статуса заказа

class OrderItemForm(ModelForm):
    class Meta:
        model = OrderItem
        fields = ['product', 'quantity']

# Создание formset для OrderItem
OrderItemFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-control py-6'}))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-control py-6'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control py-6'}))
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'form-control py-6'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-control py-6'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control py-6'}))


class ContactForm(forms.Form):
    name = forms.CharField(
        min_length=2,
        widget=forms.TextInput(
            attrs={ 'class': 'form-control'}
        )
    )

    surname = forms.CharField(
        min_length=2,
        widget=forms.TextInput(
            attrs={ 'class': 'form-control'}
        )

    )

    subject  = forms.CharField(
        min_length=2,
        widget=forms.TextInput(
            attrs={ 'class': 'form-control'}
        )

    )

    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={ 'class': 'form-control'}
        )
    )
    message = forms.CharField(
        min_length=20,
        widget=forms.Textarea(
            attrs={ 'cols' : 30, 'rows' : 7, 'class': 'form-control'}
        )
    )

class ProfileForm(forms.ModelForm):
    profile_picture = forms.ImageField(required=False, widget=forms.FileInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['profile_picture', 'first_name', 'last_name', 'email']

Main/templates/Main/about_us.html
{% extends 'base.html' %}
{% load static %}

{% block title %}О нас{% endblock %}

{% block header %}
    {% include 'inc/header.html' %}
{% endblock %}

{% block content %}

    <div class="bg-light py-3">
      <div class="container">
        <div class="row">
          <div class="col-md-12 mb-0">
            <span class="mx-2 mb-0">/</span>
            <strong class="text-black">О нас</strong>
          </div>
        </div>
      </div>
    </div>

<div class="container my-5">
    <div class="row">
        <div class="col-md-6">
            <!-- Место для фотографии -->
            <img src="{% static 'Main/images/witch.jpg' %}" class="img-fluid rounded" alt="О нас">
        </div>
        <div class="col-md-6">
            <!-- Место для текста -->
            <h2 class="mb-4 text-dark">О нас</h2>
            <p class="text-dark">Witch's Happiness – это ваш надежный магазин для предзаказа уникальных товаров из рубежа. Мы предлагаем доступ к редким предметмам эзотерики, от кристаллов до таро-карт, чтобы поддержать ваш духовный путь, которые сложно найти в обычных магазинах.</p>

            <p class="text-dark">Мы гарантируем высокое качество товаров и индивидуальный подход к каждому клиенту. Наши услуги включают простоту предзаказа и полное консультирование после, которые удовлетворят ваши ожидания.</p>

            <p class="text-dark">Выбирайте нас, чтобы открыть для себя уникальные товары и насладиться отличным обслуживанием!</p>
        </div>
    </div>
</div>
<div class="container my-5">
    <div class="row">
        <div class="col-md-12">
            <h3 class="mb-4 text-dark">Как происходит предзаказ</h3>
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">1. Зарегистрируйтесь или войдите в аккаунт</h5>
                    <p class="card-text">Для доступа к корзине и возможности оформления заказа необходимо зарегистрироваться или войти в свой аккаунт. Если у вас еще нет учетной записи, вы можете создать ее на странице регистрации.</p>

                    <h5 class="card-title">2. Ознакомьтесь с каталогом и добавьте товары в корзину</h5>
                    <p class="card-text">Перейдите в наш каталог, выберите интересующие вас товары и добавьте их в корзину. При необходимости, вы можете продолжить покупки и возвращаться к каталогу снова.</p>

                    <h5 class="card-title">3. Оформите заказ</h5>
                    <p class="card-text">Когда все выбранные товары будут в корзине, перейдите к оформлению заказа. Данные для заказа автоматически будут взяты из вашего личного кабинета, поэтому вам не потребуется заполнять дополнительные формы.</p>

                    <h5 class="card-title">4. Получите инструкции по email</h5>
                    <p class="card-text">После оформления заказа вы получите на указанную почту письмо с инструкциями по дальнейшим шагам, включая информацию о получении и оплате товаров.</p>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Встроенные стили -->
<style>
    .text-dark {
        color: #000000; /* Черный цвет текста */
    }
    .img-fluid {
        width: 100%; /* Заполняет всю ширину контейнера */
        height: auto; /* Сохраняет пропорции */
    }
    .container {
        padding: 0 15px; /* Отступы по бокам контейнера */
    }
    .my-5 {
        margin-top: 3rem; /* Отступ сверху */
        margin-bottom: 3rem; /* Отступ снизу */
    }
    .rounded {
        border-radius: .25rem; /* Округление углов изображения */
    }
    .mb-4 {
        margin-bottom: 1.5rem; /* Отступ снизу */
    }
    .card-title {
        font-size: 1.25rem; /* Размер заголовка в карточке */
        color: #333; /* Темно-серый цвет текста заголовка */
    }
    .card-text {
        font-size: 1rem; /* Размер текста в карточке */
        color: #555; /* Средне-серый цвет текста */
    }
    .container {
        padding: 0 15px; /* Отступы по бокам контейнера */
    }
    .my-5 {
        margin-top: 3rem; /* Отступ сверху */
        margin-bottom: 3rem; /* Отступ снизу */
    }
</style>
{% endblock %}

Main/templates/Main/cart.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Корзина{% endblock %}

{% block header %}
    {% include 'inc/header.html' %}
{% endblock %}

{% block content %}
    <div class="bg-light py-3">
        <div class="container">
            <div class="row">
                <div class="col-md-12 mb-0">
                    <span class="mx-2 mb-0">/</span>
                    <strong class="text-black">Корзина</strong>
                </div>
            </div>
        </div>
    </div>

    <div class="site-section">
        <div class="container">
            {% if basket %}
                <div class="row">
                    {% for item in basket %}
                        {% with prod_obj=item.product %}
                        <div class="col-md-4 mb-4">
                            <div class="card">
                                <img src="{% if prod_obj.photo and prod_obj.photo.url %}{{ prod_obj.photo.url }}{% else %}{% static 'Main/img/lol.png' %}{% endif %}" class="card-img-top" alt="Image">
                                <div class="card-body">
                                    <h5 class="card-title">
                                        <a class="text-black" href="{% url 'productt' prod_obj.pk %}">
                                            {{ prod_obj.name }}
                                        </a>
                                    </h5>
                                    <p class="card-text">Цена: {{ item.price_prod }}</p>
                                    <p class="card-text">Количество: {{ item.count_prod }}</p>
                                    <p class="card-text">Всего: {{ item.total_price }}</p>
                                    <a href="{% url 'remove_basket_prod' prod_obj.pk %}" class="btn btn-primary">Удалить</a>
                                </div>
                            </div>
                        </div>
                        {% endwith %}
                    {% endfor %}
                </div>

                <div class="row mt-4">
                    <div class="col-md-6">
                        <a href="{% url 'clear_basket_prod' %}" class="btn btn-primary btn-md btn-block">Очистить корзину</a>
                        <a href="{% url 'catalog' %}" class="btn btn-outline-primary btn-md btn-block">Продолжить покупки</a>
                    </div>
                    <div class="col-md-6">
                        <div class="border p-3">
                            <h4 class="text-uppercase">Итоговая сумма</h4>
                            <div class="row mb-3">
                                <div class="col-6">Промежуточный итог</div>
                                <div class="col-6 text-right">{{ basket.get_total_price }}</div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-6">Итого</div>
                                <div class="col-6 text-right">{{ basket.get_total_price }}</div>
                            </div>
                            <form action="{% url 'create_order' %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-outline-primary btn-md btn-block">Оформить заказ</button>
                            </form>
                        </div>
                    </div>
                </div>
            {% else %}
                <div class="text-center py-5">
                    <h2 class="h4 text-black mb-4">Ваша корзина пуста</h2>
                    <p class="text-muted mb-4">Вы можете вернуться в каталог и добавить товары в корзину.</p>
                    <a href="{% url 'catalog' %}" class="btn btn-primary btn-lg">Вернуться в каталог</a>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

Main/templates/Main/edit_profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Редактирование профиля{% endblock %}

{% block header %}
    {% include 'inc/header.html' %}
{% endblock %}

{% block content %}
<style>
    /* Стили для формы редактирования профиля */
    .btn-custom {
        background-color: white;
        color: #343a40;
        border: 2px solid #343a40;
        transition: background-color 0.3s, color 0.3s, border-color 0.3s;
    }

    .btn-custom:hover {
        background-color: #343a40;
        color: white;
        border-color: #343a40;
    }

    .profile-picture {
        width: 200px;
        height: 200px;
        object-fit: cover;
        border-radius: 50%;
        margin-bottom: 20px;
    }

    .form-control {
        margin-bottom: 20px;
    }

    .profile-info {
        margin-top: 20px;
    }

    .btn-profile {
        margin-right: 10px;
    }
</style>

<div class="bg-light py-3">
  <div class="container">
    <div class="row">
      <div class="col-md-12 mb-0">
        <span class="mx-2 mb-0">/</span>
        <strong class="text-black">Редактирование профиля</strong>
      </div>
    </div>
  </div>
</div>

<div class="container my-5">
    <div class="row">
        <div class="col-md-4 text-center">
            <!-- Пользовательская фотография -->
            <div class="mb-4">
                <img src="{% if user.profile_picture %}{{ user.profile_picture.url }}{% else %}{% static 'Main/img/lol.png' %}{% endif %}"
                     alt="Profile Picture"
                     class="profile-picture">
            </div>
        </div>

        <div class="col-md-8 profile-info">
            <!-- Форма редактирования профиля -->
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_profile_picture">Изменить фото профиля</label>
                    {{ form.profile_picture }}
                </div>
                <div class="form-group">
                    <label for="id_first_name">Имя</label>
                    {{ form.first_name }}
                </div>
                <div class="form-group">
                    <label for="id_last_name">Фамилия</label>
                    {{ form.last_name }}
                </div>
                <div class="form-group">
                    <label for="id_email">Email</label>
                    {{ form.email }}
                </div>

                <!-- Кнопки сохранения и отмены -->
                <div class="mt-4">
                    <button type="submit" class="btn btn-custom btn-md btn-profile">Сохранить изменения</button>
                    <a href="{% url 'profile' %}" class="btn btn-custom btn-md">Отменить</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

Main/templates/Main/header.html
 <div class="site-navbar py-2">

      <div class="search-wrap">
        <div class="container">
          <a href="#" class="search-close js-search-close"><span class="icon-close2"></span></a>
          <form action="#" method="post">
            <input type="text" class="form-control" placeholder="Search keyword and hit enter...">
          </form>
        </div>
      </div>

       <div class="container">
        <div class="d-flex align-items-center justify-content-between">
          <div class="logo">
            <div class="site-logo">
              <a href="{% url 'index' %}" class="js-logo-clone">witch's happiness</a>
            </div>
          </div>
          <div class="main-nav d-none d-lg-block">
            <nav class="site-navigation text-right text-md-center" role="navigation">
              <ul class="site-menu js-clone-nav d-none d-lg-block">
                <li><a href="{% url 'index' %}">Главная</a></li>
                <li><a href="{% url 'catalog' %}">Каталог</a></li>
                <li><a href="{% url 'api' %}">API</a></li>
                <li><a href="{% url 'contact' %}">Обратная связь</a></li>
                <li><a href="{% url 'order' %}">Заказ</a></li>
              </ul>
            </nav>
          </div>


            <div class="icons">
            {% if request.user.is_authenticated %}
            <div class="main-nav d-none d-lg-block">
            <nav class="site-navigation text-right text-md-center" role="navigation">
              <ul class="site-menu js-clone-nav d-none d-lg-block">
            <li> {{user.username}} | <a href="{% url 'logout' %}">Выйти</a></li>
            {% else %}
            <a href="{% url 'login' %}" class="icons-btn d-inline-block icon-person"></a>
            {% endif %}
            <a href="{% url 'cart' %}" class="icons-btn d-inline-block js-search-open"><span class="icon-search"></span></a>
            <a href="{% url 'cart' %}" class="icons-btn d-inline-block bag">
              <span class="icon-shopping-bag"></span>
              <span class="number">2</span>
            </a>
            <a href="#" class="site-menu-toggle js-menu-toggle ml-3 d-inline-block d-lg-none"><span
                class="icon-menu"></span></a>
          </div>
        </div>
      </div>
    </div>

Main/templates/Main/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Witch Happiness{% endblock %}

{% block content %}
    <!-- Hero Section -->
    <div class="site-blocks-cover" style="background-image: url({% static 'Main/images/shop.png' %});">
        <div class="container">
            <div class="row">
                <div class="col-lg-7 mx-auto order-lg-2 align-self-center">
                    <div class="site-block-cover-content text-center">
                        <h2 class="sub-title">Mystical Remedies, Enchanting Elixirs, Spellbinding Potions</h2>
                        <h1>Welcome Home, Witch</h1>
                        <p>
                            <a href="{% url 'catalog' %}" class="btn btn-primary px-5 py-3">Оформить заказ сейчас.</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="site-section bg-light">
        <div class="container">
            <div class="row align-items-stretch section-overlap">
                <div class="col-md-6 col-lg-4 mb-4 mb-lg-0">
                    <div class="banner-wrap bg-dark text-white h-100 d-flex flex-column justify-content-center align-items-center">
                        <a  class="text-white text-center">
                            <h5>Эксклюзивные Товары</h5>
                            <p>
                                У нас уникальные эзотерические предметы, которые сложно найти где-либо еще.
                            </p>
                        </a>
                    </div>
                </div>
                <div class="col-md-6 col-lg-4 mb-4 mb-lg-0">
                    <div class="banner-wrap bg-dark text-white h-100 d-flex flex-column justify-content-center align-items-center">
                        <a  class="text-white text-center">
                            <h5>Качество и Надежность</h5>
                            <p>
                                Мы гарантируем высокое качество всех наших товаров.
                            </p>
                        </a>
                    </div>
                </div>
                <div class="col-md-6 col-lg-4 mb-4 mb-lg-0">
                    <div class="banner-wrap bg-dark text-white h-100 d-flex flex-column justify-content-center align-items-center">
                        <a  class="text-white text-center">
                            <h5>Международная Доставка</h5>
                            <p>
                                Доставка уникальных товаров со всего мира.
                            </p>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Products Section -->
    <div class="site-section bg-light">
        <div class="container">
            <div class="row">
                <div class="title-section text-center col-12">
                    <h2 class="text-uppercase">Наша продукция</h2>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 block-3 products-wrap">
                    <div class="nonloop-block-3 owl-carousel">
                        {% for model in objects %}
                            <div class="text-center item mb-4">
                                {% if model.photo %}
                                    <a href="{% url 'productt' model.pk %}"><img src="{{ model.photo.url }}" alt="Image"></a>
                                    <h3 class="text-dark"><a href="{% url 'productt' model.pk %}">{{ model.name }}</a></h3>
                                    <p class="price">{{ model.price }}</p>
                                {% else %}
                                    <a href="{% url 'productt' model.pk %}"><img src="{% static 'Main/img/lol.png' %}" alt="Image"></a>
                                    <h3 class="text-dark"><a href="{% url 'productt' model.pk %}">{{ model.name }}</a></h3>
                                    <p class="price">{{ model.price }}</p>
                                {% endif %}
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Main/templates/Main/orderfinish.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Оформление заказа{% endblock %}

{% block content %}
    <div class="text-center">
        <!-- Картинка -->
        <img src="{% static 'Main/images/witch.JPG' %}" alt="Аниме персонаж" style="width: 400px; height: 400px;">

        <!-- Краткое сообщение -->
        <p style="margin-top: 20px; font-size: 24px; color: #333;">
            Ваш заказ успешно оформлен.<br> Ожидайте, пожалуйста, дальнейших инструкций по электронной почте.
        </p>
    </div>
{% endblock %}

Main/templates/Main/profile_deleted.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Профиль удален{% endblock %}

{% block content %}
<div class="bg-light py-3">
      <div class="container">
        <div class="row">
          <div class="col-md-12 mb-0">
            <span class="mx-2 mb-0">/</span>
            <strong class="text-black">Удаление профиля</strong>
          </div>
        </div>
      </div>
    </div>
 <div class="site-section">
<div class="container my-5">
    <h2 class="text-center">Ваш профиль был успешно удален.</h2>
    <div class="text-center mt-4">
        <a href="{% url 'index' %}" class="btn btn-primary">На главную</a>
    </div>
</div>
     </div>
{% endblock %}