Main/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.conf import settings
from .import views
from .views import order_finish, create_order, ProfileDeletedView

urlpatterns = [
    path('', views.index.as_view(), name='index'),
    path('catalog/', views.catalog.as_view(), name='catalog'),
    path('contact/', views.contact, name='contact'),
    path('login/', views.login.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register.as_view(), name='register'),
    path('catalog/create', views.createproduct.as_view(), name='createproduct'),
    path('api/', views.api, name='api'),
    path('apidelete', views.apidelete, name='apidelete'),
    path('apicreate', views.apicreate, name='apicreate'),
    path('apiedit', views.apiedit, name='apiedit'),
    path('apiselectmany', views.apiselectmany, name='apiselectmany'),
    path('apiselectone', views.apiselectone, name='apiselectone'),
    path('catalog/<int:pk>/', views.productt.as_view(), name='productt'),
    path('catalog/category/<int:category_id>/', views.FilteredCatalogView.as_view(), name='category'),
    path('catalog/tag/<int:pk>/', views.TagDetailView.as_view(), name='tag'),
    path('catalog/<int:pk>/update', views.update.as_view(), name='update'),
    path('catalog/<int:pk>/delete', views.delete.as_view(), name='delete'),
    path('catalog/createcategory', views.createcategory.as_view(), name='createcategory'),
    path('catalog/CreateTag', views.CreateTag.as_view(), name='CreateTag'),
    path('filter_by_price/', views.filter_by_price, name='filter_by_price'),
    path('order/', views.order.as_view(), name='order'),
    path('create-order/', create_order, name='create_order'),
    path('order-finish/', order_finish, name='order_finish'),
    path('order/create', views.createorder.as_view(), name='createorder'),
    path('order/detail/<int:pk>/', views.detailorder.as_view(), name='detailorder'),
    path('order/update/<int:pk>/', views.updateorder.as_view(), name='updateorder'),
    path('order/delete/<int:pk>/', views.deleteorder.as_view(), name='deleteorder'),

    path('cart/', views.basket_info, name='cart'),
    path('cart/add/<int:product_id>/', views.basket_add, name='add_basket_prod'),
    path('cart/remove/<int:product_id>/', views.basket_remove, name='remove_basket_prod'),
    path('cart/clear/', views.basket_clear, name='clear_basket_prod'),
    path('cart/finish/', order_finish, name='order_finish'),

    path('about_us/', views.about_us, name='about_us'),

    path('profile/', views.profile, name='profile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('delete-profile/', views.ProfileDeleteView.as_view(), name='delete_profile'),
    path('profile-deleted/', ProfileDeletedView.as_view(), name='profile_deleted'),

    # Api
    path('api/', views.api, name='api'),
    # категории
    path('api/category/', views.ApiCategoryList.as_view(), name='api_category'),
    path('api/category/create/', views.ApiCategoryCreate.as_view(), name='api_category_create'),
    path('api/category/<int:pk>/', views.ApiCategoryDetail.as_view(), name='api_category_detail'),
    path('api/category/update/<int:pk>/', views.ApiCategoryUpdate.as_view(), name='api_category_update'),
    path('api/category/delete/<int:pk>/', views.ApiCategoryDelete.as_view(), name='api_category_delete'),
    # продукты
    path('api/product/', views.ApiModel_and_tochkaList.as_view(), name='api_product'),
    path('api/product/create/', views.ApiModel_and_tochkaCreate.as_view(), name='api_product_create'),
    path('api/product/<int:pk>/', views.ApiModel_and_tochkaDetail.as_view(), name='api_product_detail'),
    path('api/product/update/<int:pk>/', views.ApiCategoryUpdate.as_view(), name='api_product_update'),
    path('api/product/delete/<int:pk>/', views.ApiModel_and_tochkaDelete.as_view(), name='api_product_delete'),
    # тэги
    path('api/tag/', views.ApiTagList.as_view(), name='api_tag'),
    path('api/tag/create/', views.ApiTagCreate.as_view(), name='api_tag_create'),
    path('api/tag/<int:pk>/', views.ApiTagDetail.as_view(), name='api_tag_detail'),
    path('api/tag/update/<int:pk>/', views.ApiTagUpdate.as_view(), name='api_tag_update'),
    path('api/tag/delete/<int:pk>/', views.ApiModel_and_tochkaDelete.as_view(), name='api_tag_delete'),
]

MyShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Main.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Catalog/models.py
from django.db import models

# Create your models here.

Main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=45, verbose_name='Название')
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'Категории'

    def get_absolute_url(self):
        return '/catalog'


class Model_and_tochka(models.Model):
    category = models.ForeignKey(Category, on_delete=models.PROTECT, verbose_name='Категория', null=True)
    name = models.CharField(max_length=45, default='Product', verbose_name='Название')
    description = models.TextField(blank=True, verbose_name='Описание')
    price = models.FloatField(default=10, verbose_name='Цена')
    data_add = models.DateField(auto_now_add=True, verbose_name='Дата добавления')
    data_update = models.DateTimeField(auto_now=True, verbose_name='Дата изменения')
    exist = models.BooleanField(default=True, verbose_name='Существует?')
    photo = models.ImageField(upload_to='image/%Y/%m/%d', null=True, verbose_name='Изображения', blank=True)
    country_of_origin = models.CharField(max_length=100, blank=True, null=True, verbose_name='Страна производителя')

    def __str__(self):
        return f'{self.name} - {self.price}'

    def get_absolute_url(self):
        return f'/catalog/{self.pk}'

    def delete(self, using=None, keep_parents=False):
        self.exist = False
        self.save()

    class Meta:
        verbose_name = 'товар'
        verbose_name_plural = 'Товары'
        ordering = ['-price', 'name']


class Tag(models.Model):
    name = models.CharField(max_length=45, verbose_name='Название')
    description = models.TextField(blank=True, verbose_name='Описание')
    products = models.ManyToManyField('Model_and_tochka', related_name='tags', verbose_name='Товары')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/catalog/tag/{self.pk}'

    class Meta:
        verbose_name = 'тег'
        verbose_name_plural = 'Теги'
        ordering = ['name']



class Order(models.Model):
    STATUS_CHOICES = [
        ('processing', 'В обработке'),
        ('completed', 'Выполнен'),
        ('cancelled', 'Отменён'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь', null=True, blank=True)
    email = models.EmailField(verbose_name='Email пользователя', blank=True, null=True)
    creation_date = models.DateField(auto_now_add=True, verbose_name='Дата создания')
    products = models.ManyToManyField('Model_and_tochka', through='OrderItem', verbose_name='Товары')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='processing', verbose_name='Статус заказа')
    exist = models.BooleanField(default=True, verbose_name='Существует?')

    def __str__(self):
        return f'Order by {self.user.username if self.user else "Unknown"} on {self.creation_date}'

    def save(self, *args, **kwargs):
        if self.user:
            self.email = self.user.email  # Автоматически заполняем поле email почтой пользователя
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'заказ'
        verbose_name_plural = 'Заказы'




class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name='Заказ')
    product = models.ForeignKey('Model_and_tochka', on_delete=models.CASCADE, verbose_name='Товар и его цена')
    quantity = models.PositiveIntegerField(verbose_name='Количество товаров на позиции', default=1)


    def __str__(self):
        return f'{self.order} - {self.product}'

    class Meta:
        verbose_name = 'позиция заказа'
        verbose_name_plural = 'Позиции заказа'

Main/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from .models import Model_and_tochka, Category, Tag, Order, OrderItem
from django.forms import ModelForm, TextInput, Textarea, inlineformset_factory
from django import forms
from django.contrib.auth.models import User
from .models import Order


class Model_and_tochkaForm(ModelForm):


    class Meta:
        model = Model_and_tochka
        fields = ['category', 'name', 'description', 'price', 'photo', 'country_of_origin']
        widgets = {
            "name": TextInput(attrs={
                'class': 'form-control py-6',
                'placeholder': ''
            }),
            "description": Textarea(attrs={
                'class': 'form-control'
            })
        }

class CategoryForm(ModelForm):

    class Meta:
        model = Category
        fields = ['description', 'name']
        widgets = {
            "name": TextInput(attrs={
                'class': 'form-control py-6',
                'placeholder': ''
            }),
            "description": Textarea(attrs={
                'class': 'form-control'
            })
    }
class TagForm(ModelForm):

    class Meta:
        model = Tag
        fields = ['description', 'name', 'products']
        widgets = {
            "name": TextInput(attrs={
                'class': 'form-control py-6',
                'placeholder': ''
            }),
            "description": Textarea(attrs={
                'class': 'form-control'
            })
    }

PROD_MAX_COUNT = [(i, str(i)) for i in range(1, 25)]


class BasketAddProductForm(forms.Form):
    count_prod = forms.TypedChoiceField(choices=PROD_MAX_COUNT, coerce=int, label='Количество')
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['user', 'status']  # Поля для выбора пользователя и статуса заказа

class OrderItemForm(ModelForm):
    class Meta:
        model = OrderItem
        fields = ['product', 'quantity']

# Создание formset для OrderItem
OrderItemFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-control py-6'}))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-control py-6'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control py-6'}))
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'form-control py-6'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-control py-6'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control py-6'}))


class ContactForm(forms.Form):
    name = forms.CharField(
        min_length=2,
        widget=forms.TextInput(
            attrs={ 'class': 'form-control'}
        )
    )

    surname = forms.CharField(
        min_length=2,
        widget=forms.TextInput(
            attrs={ 'class': 'form-control'}
        )

    )

    subject  = forms.CharField(
        min_length=2,
        widget=forms.TextInput(
            attrs={ 'class': 'form-control'}
        )

    )

    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={ 'class': 'form-control'}
        )
    )
    message = forms.CharField(
        min_length=20,
        widget=forms.Textarea(
            attrs={ 'cols' : 30, 'rows' : 7, 'class': 'form-control'}
        )
    )

class ProfileForm(forms.ModelForm):
    profile_picture = forms.ImageField(required=False, widget=forms.FileInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['profile_picture', 'first_name', 'last_name', 'email']

Catalog/views.py
from django.shortcuts import render

# Create your views here.

Catalog/templates/Catalog/Base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <title>{% block title %}Каталог{% endblock %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link href="https://fonts.googleapis.com/css?family=Rubik:400,700|Crimson+Text:400,400i" rel="stylesheet">
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'Main/fonts/icomoon/style.css' %}">
  <link rel="stylesheet" href="{% static 'Main/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'Main/css/magnific-popup.css' %}">
  <link rel="stylesheet" href="{% static 'Main/css/jquery-ui.css' %}">
  <link rel="stylesheet" href="{% static 'Main/css/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'Main/css/owl.theme.default.min.css' %}">
  <link rel="stylesheet" href="{% static 'Main/css/aos.css' %}">
  <link rel="stylesheet" href="{% static 'Main/css/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">

  <style>
          .card p.price {
          font-size: 1rem;
          color: #007bff;
          margin-bottom: 10px;
      }

      .card img {
    border-top-left-radius: 10px;
    border-top-right-radius: 10px;
    width: 100%;
    height: 200px;
    object-fit: cover;
}

      .card:hover {
    box-shadow: 0 8px 20px rgba(0, 0, 0, 0.1);
}
    /* Стили для кнопок "Создать товар" и "Создать категорию" */
    .btn-custom {
      background-color: white;
      color: #343a40;
      border: 2px solid #343a40;
      transition: background-color 0.3s, color 0.3s, border-color 0.3s;
    }

    .btn-custom:hover {
      background-color: #343a40;
      color: white;
      border-color: #343a40;
    }

    /* Стили для кнопок пагинации */
    .pagination .page-item {
      margin: 0 5px;
    }

    .pagination .page-item .page-link {
      color: #343a40;
      border-radius: 50px;
      border: 1px solid #343a40;
      padding: 10px 20px;
      box-shadow: 0 2px 5px rgba(0, 0, 0, 0.15);
      transition: background-color 0.3s, color 0.3s, box-shadow 0.3s;
      display: flex;
      justify-content: center;
      align-items: center;
      text-align: center;
    }

    .pagination .page-item.active .page-link {
      background-color: #343a40;
      color: white;
      border-color: #343a40;
    }

    .pagination .page-item .page-link:hover {
      background-color: #495057;
      color: white;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
    }

    /* Центрирование модального окна */
    .modal-dialog {
      max-width: 600px;
      margin: 1.75rem auto;
    }

    /* Обеспечивает видимость модального окна */
    .modal-content {
      border-radius: .3rem;
    }

    /* Ограничение высоты выпадающего меню и добавление скролла */
    .dropdown-menu {
      max-height: 400px;
      overflow-y: auto;
    }

    @media (max-width: 767px) {
    .card img {
        height: 150px;
    }
}

/* Уплотнение карточек на мобильных устройствах */
@media (max-width: 576px) {
    .col-sm-4 {
        flex: 0 0 50%;
        max-width: 50%;
    }

    .card-body {
        padding: 10px;
    }
}

  </style>
</head>

<body>
  {% block header %}
    {% include 'inc/header.html' %}
  {% endblock %}

  {% block catalog %}{% endblock %}

  {% block content %}{% endblock %}
  <div class="site-section">
    <div class="container">
      <div class="row mb-4">
        <div class="col-lg-6 mb-3 mb-lg-0">
          <div class="dropdown">
            <button type="button" class="btn btn-secondary btn-md dropdown-toggle px-4" id="dropdownMenuReference" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Категории
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuReference">
              {% for category in categories %}
              <a class="dropdown-item" href="{% url 'category' category.pk %}">{{ category.name }}</a>
              {% endfor %}
            </div>
          </div>
        </div>

        {% if user.is_staff %}
        <div class="col-lg-6 d-flex justify-content-lg-end justify-content-center">
          <a href="{% url 'createproduct' %}" class="btn btn-custom btn-md mr-2">Создать товар</a>
          <a href="{% url 'createcategory' %}" class="btn btn-custom btn-md">Создать категорию</a>
        </div>
        {% endif %}
      </div>

      <div class="site-section bg-light">
        <div class="container">
          <div class="row">
            {% if objects %}
              {% for model in objects %}
                <div class="col-sm-4 mb-4">
                  <a href="{% url 'productt' model.pk %}">
                    <img src="{% if model.photo %}{{ model.photo.url }}{% else %}{% static 'Main/img/lol.png' %}{% endif %}" class="card-img-top" alt="...">
                  </a>
                  <div class="card-body">
                    <h5 class="text-dark text-center">{{ model.name }}</h5>
                    <p class="price text-center">{{ model.price }}</p>
                  </div>
                </div>
              {% endfor %}
            {% else %}
              <p>Нет товаров по вашему запросу.</p>
            {% endif %}
          </div>

          <!-- Пагинация -->
          <div class="row mt-5">
            <div class="col-md-12 text-center">
              <div class="site-block-27">
                <ul class="pagination justify-content-center">
                  {% if objects.has_previous %}
                  <li class="page-item">
                    <a class="page-link" href="{{ page_links.first }}">&laquo;&laquo;</a>
                  </li>
                  <li class="page-item">
                    <a class="page-link" href="{{ page_links.previous }}">{{ objects.previous_page_number }}</a>
                  </li>
                  {% endif %}

                  <li class="page-item active">
                    <span class="page-link">{{ objects.number }} <span class="sr-only">(current)</span></span>
                  </li>

                  {% if objects.has_next %}
                  <li class="page-item">
                    <a class="page-link" href="{{ page_links.next }}">{{ objects.next_page_number }}</a>
                  </li>
                  <li class="page-item">
                    <a class="page-link" href="{{ page_links.last }}">&raquo;&raquo;</a>
                  </li>
                  {% endif %}
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  {% block footer %}
    {% include 'inc/footer.html' %}
  {% endblock %}

  <!-- Подключаем скрипты в правильном порядке -->
  <!-- Подключаем jQuery -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <!-- Подключаем Popper.js -->
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
  <!-- Подключаем Bootstrap JS -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <script>
  $(document).ready(function() {
    $('.dropdown-toggle').on('click', function(event) {
      var $el = $(this).next('.dropdown-menu');
      var isVisible = $el.is(':visible');
      $('.dropdown-menu').hide();
      if (!isVisible) {
        $el.show();
      }
    });
  });
</script>
  <script>
    document.addEventListener('DOMContentLoaded', function() {
      const menuToggle = document.querySelector('.js-menu-toggle');
      const mobileMenu = document.querySelector('.mobile-menu');

      menuToggle.addEventListener('click', function() {
        mobileMenu.classList.toggle('active');
      });

      const menuClose = document.querySelector('.search-close');
      menuClose.addEventListener('click', function() {
        mobileMenu.classList.remove('active');
      });
    });
  </script>
  <script src="{% static 'Main/js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'Main/js/jquery-ui.js' %}"></script>
  <script src="{% static 'Main/js/popper.min.js' %}"></script>
  <script src="{% static 'Main/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'Main/js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'Main/js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'Main/js/aos.js' %}"></script>
  <script src="{% static 'Main/js/main.js' %}"></script>
  <script src="{% static 'js/order_form.js' %}"></script>

</body>

</html>

Catalog/templates/Catalog/BaseTag.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <title>{% block title %}{% endblock %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link href="https://fonts.googleapis.com/css?family=Rubik:400,700|Crimson+Text:400,400i" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'Main/fonts/icomoon/style.css' %}">

  <link rel="stylesheet" href="{% static 'Main/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'Main/css/magnific-popup.css' %}">
  <link rel="stylesheet" href="{% static 'Main/css/jquery-ui.css' %}">
  <link rel="stylesheet" href="{% static 'Main/css/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'Main/css/owl.theme.default.min.css' %}">


  <link rel="stylesheet" href="{% static 'Main/css/aos.css' %}">
  <link rel="stylesheet" href="{% static 'Main/css/style.css' %}">

</head>
<body>
  {% block header %}
    {% include 'Catalog/header.html' %}
  {% endblock %}

  {% block catalog %}{% endblock %}

  {% block content %}

  <div class="site-section">
    <div class="container">
      <div class="row">
        <div class="col-lg-6">
          <!-- Кнопка "Категории" -->
          <button type="button" class="btn btn-secondary btn-md dropdown-toggle px-4" id="dropdownMenuReference" data-toggle="dropdown">Категории</button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuReference">
            {% for category in categories %}
            <a class="dropdown-item" href="{% url 'category' category.pk %}">{{ category.name }}</a>
            {% endfor %}
          </div>
        </div>
        <div class="col-lg-6">
          <!-- Кнопка "Продолжить покупки" -->
          <div class="row">
            <div class="col-md">
              <a href="{% url 'createproduct' %}">
                <button class="btn btn-secondary btn-md btn-block">Создать товар</button>
              </a>
            </div>
          </div>
        </div>
      </div>

      <div class="site-section bg-light">
        <div class="container">
          <div class="row">
            {% for model in objects %}
              {% if model.photo %}
                <div class="col-sm-4" style="width: 18rem;">
                  <a href="{% url 'productt' model.pk %}"><img src="{{ model.photo.url }}" class="card-img-top" alt="..."></a>
                  <div class="card-body">
                    <h5 class="text-dark text-center">{{ model.name }}</h5>
                    <p class="price text-center">{{ model.price }}</p>
                  </div>
                </div>
              {% else %}
                <div class="col-sm-4" style="width: 18rem;">
                  <a href="{% url 'productt' model.pk %}"><img src="{% static 'Main/img/lol.png' %}" class="card-img-top" alt="..."></a>
                  <div class="card-body">
                    <h5 class="text-dark">{{ model.name }}</h5>
                    <p class="price text-center">{{ model.price }}</p>
                  </div>
                </div>
              {% endif %}
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

  {% block footer %}
    {% include 'inc/footer.html' %}
  {% endblock %}

  <script src="{% static 'Main/js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'Main/js/jquery-ui.js' %}"></script>
  <script src="{% static 'Main/js/popper.min.js' %}"></script>
  <script src="{% static 'Main/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'Main/js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'Main/js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'Main/js/aos.js' %}"></script>
  <script src="{% static 'Main/js/main.js' %}"></script>
</body>
</html>

Catalog/templates/Catalog/edit.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Изменение товара{% endblock %}

{% block content %}
<div class="bg-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a href="{% url 'index' %}">Главная</a>
                <span class="mx-2 mb-0">/</span>
                <a href="{% url 'catalog' %}">Каталог</a>
                <span class="mx-2 mb-0">/</span>
                <strong class="text-black">Изменение товара</strong>
            </div>
        </div>
    </div>
</div>

<div class="site-section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2 class="h3 mb-5 text-black">Изменение товара</h2>
            </div>
            <div class="col-md-12">

                <form action="#" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="p-3 p-lg-5 border">
                        <div class="form-group row">
                            <div class="col-md-6">
                                <label for="id_name" class="text-black">Введите новое название товара</label>
                                {{ form.name }}
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-md-12">
                                <label for="id_photo" class="text-black">Выберите файл <span class="text-danger">*</span></label>
                                {{ form.photo }}
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-md-12">
                                <label for="id_category" class="text-black">Выберите категорию <span class="text-danger">*</span></label>
                                {{ form.category }}
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-md-6">
                                <label for="id_price" class="text-black">Введите цену товара</label>
                                {{ form.price }}
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-md-12">
                                <label for="id_description" class="text-black">Введите новое описание товара</label>
                                {{ form.description }}
                            </div>
                        </div>

                        <!-- Новое поле для страны производителя -->
                        <div class="form-group row">
                            <div class="col-md-6">
                                <label for="id_country_of_origin" class="text-black">Страна производителя</label>
                                {{ form.country_of_origin }}
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-lg-12">
                                <input type="submit" class="btn btn-primary btn-lg btn-block" value="Сохранить изменения">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <span>{{ error }}</span>
        </div>
    </div>
</div>
{% endblock %}